const SET_DETAIL_MOVIE = "SET_DETAIL_MOVIE";
const LOAD_MOVIES = "LOAD_MOVIES";

const GET_MOVIES = "GET_MOVIES";
const SET_FILTER = "SET_FILTER";

export { SET_DETAIL_MOVIE, GET_MOVIES, LOAD_MOVIES, SET_FILTER };
