const SET_DETAIL_MOVIE = "SET_DETAIL_MOVIE";
const LOAD_MOVIES = "LOAD_MOVIES";
const SET_MOVIES = "SET_MOVIES";

const SET_SEARCH_TERM = "SET_SEARCH_TERM";
const SET_ACTIVE_PAGE = "SET_ACTIVE_PAGE";
const SET_RESULT_COUNT = "SET_RESULT_COUNT";

const GET_MOVIES = "GET_MOVIES";
const SET_FILTER = "SET_FILTER";

export {
	SET_DETAIL_MOVIE,
	GET_MOVIES,
	LOAD_MOVIES,
	SET_MOVIES,
	SET_FILTER,
	SET_SEARCH_TERM,
	SET_ACTIVE_PAGE,
	SET_RESULT_COUNT,
};
